# Generated by Django 3.2.6 on 2021-08-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_rename_projecttask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='todo_list.project'),
        ),
    ]
